TsubakiBotPad/tsutils

.gitignore, setup.py, tsutils/cog_settings.py, tsutils/formatting.py, tsutils/helper_classes.py, tsutils/helper_functions.py, tsutils/json_utils.py, tsutils/menu.py, tsutils/user_interaction.py
Breaking Changes:
* Changes casing in many commands, but only three are used in Tsubaki code:
* makeAsyncCachedPlainRequest -> make_async_cached_plain_request
* containsJa -> contains_ja
* normalizeServer -> normalize_server
* EmojiUpdater.on_update is now a coroutine
=> Tsutils Update

setup.py, tsutils/menu.py, tsutils/user_interaction.py
requirement for https://github.com/TsubakiBotPad/pad-cogs/issues/624
=> Add getreaction

tsutils/user_interaction.py
Provides the basis for https://github.com/TsubakiBotPad/pad-cogs/issues/590
=> Add status context manager

setup.py, tsutils/emoji.py
Required for https://github.com/TsubakiBotPad/pad-cogs/pull/812
=> Cast ints & support 10 in char_to_emoji

setup.py, tsutils/menu/footers.py
This also allows the base image to be optionally passed in
=> Change pad_info_footer -> embed_footer

setup.py, tsutils/pad.py
Necessary due to https://github.com/TsubakiBotPad/pad-cogs/pull/1029
=> Don't use monster_no in tsutils

setup.py, tsutils/enums.py, tsutils/query_settings.py
Closes https://github.com/TsubakiBotPad/pad-cogs/issues/1196
=> Add LsMultiplier & CardPlusModifier

setup.py, tsutils/enums.py, tsutils/query_settings.py
Resolves #35 
This is a BREAKING CHANGE
=> ChildMenuType to be consistent with menu2

setup.py, tsutils/errors.py, tsutils/helper_classes.py, tsutils/menu/footers.py
This doesn't bump version bc I'm about to send a second PR
=> Add text param to footer creator & Index Error

setup.py, tsutils/converters.py, tsutils/emoji.py, tsutils/enums.py, tsutils/formatting.py, tsutils/user_interaction.py
+ Adds a file for Converters with CaseInsensitiveRole included
+ Adds constants for Emoji types and yes and no emoji
+ Adds converter capabilities to Serve and new StarterGroup enums
+ Adds type hints to most files
+ Adds confirmation and cancellation commands
/ Changes `confirm_message` to `get_user_confirmation` and `get_reaction` to `get_user_reaction`
/ Removes non-ascii characters from files
=> Tsutils v4

setup.py, tsutils/menu/panes.py
Partially closes https://github.com/TsubakiBotPad/discord-menu/issues/21
=> Support menu emojis provided as tuples with fallbacks

tsutils/errors.py
This is a slightly different case, and I think it deserves its own error type.
=> Add BadAPIKeyException

setup.py, tsutils/cog_mixins.py, tsutils/helper_classes.py, tsutils/query_settings.py, tsutils/tsubaki.py
This also adds the function `tsubaki.get_user_preference` and the class `helper_classes.CogABCMeta`
=> Add cog_mixin.py

setup.py, tsutils/enums.py
=> Recognize JP server correctly

setup.py, tsutils/helper_functions.py, tsutils/time.py
=> Make conditional_iterator better

requirements.txt, setup.py
It still takes a good 10 seconds, but that's better than the many hours it took before!
=> Fix Install Issue for real

setup.py, tsutils/tsubaki.py
=> add number_emoji_small

setup.py, tsutils/tsubaki.py
https://github.com/TsubakiBotPad/pad-cogs/issues/1583
=> Add MonsterImage

setup.py, tsutils/emoji.py
This fix will work until the year 2090 when they will be 20 digits.
=> Snowflakes can be 19 digits now

tsutils/query_settings/enums.py
No version change because I'll do that in the next PR
=> Alphabetize enums

tsutils/json_utils.py
Closes #106 
fix safe_read_json to not log filenotfounderror
=> stop logging file error in safe_read_json

setup.py, tsutils/tsubaki/monster_header.py
=> changed emoji 🇺🇸

setup.py, tsutils/menu/components/footers.py, tsutils/menu/pad_view.py, tsutils/menu/view/closable_embed.py, tsutils/menu/view/simple_text.py, tsutils/tsubaki/custom_emoji.py, tsutils/tsubaki/links.py, tsutils/tsubaki/monster_header.py
TODO: add another class for ones that have both state & props
=> Support fallback images & add PadViewState
